apiVersion: v1
kind: Secret
metadata:
  name: amazon-secrets
  namespace: amazon
type: Opaque
# Values are base64-encoded. In production use Vault / AWS Secrets Manager / Sealed Secrets.
# To encode: echo -n "your-value" | base64
data:
  db-username: YW1hem9u                          # amazon
  db-password: YW1hem9uMTIz                      # amazon123
  redis-password: cmVkaXMxMjM=                   # redis123
  jwt-secret: YW1hem9uLXN1cGVyLXNlY3JldC1qd3Qta2V5LTIwMjQtbWluaW11bS0yNTYtYml0cy1yZXF1aXJlZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
  namespace: amazon
type: Opaque
data:
  bootstrap-servers: a2Fma2E6MjkwOTI=           # kafka:29092
