apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: amazon

resources:
  - namespaces/namespace.yaml
  - secrets/secrets.yaml
  - configmaps/configmaps.yaml
  - infrastructure/infrastructure.yaml
  - monitoring/monitoring.yaml
  - services/services.yaml
  - hpa/hpa.yaml
  - ingress/ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: amazon-microservices

images:
  - name: amazon/api-gateway
    newTag: "1.0.0"
  - name: amazon/user-service
    newTag: "1.0.0"
  - name: amazon/product-service
    newTag: "1.0.0"
  - name: amazon/order-service
    newTag: "1.0.0"
  - name: amazon/payment-service
    newTag: "1.0.0"
  - name: amazon/notification-service
    newTag: "1.0.0"
